### ISSUE TITLE
immutable-diff patch

### ISSUE THREAD

**Issue by azproduction** [tgriesser/immutable-diff#2]
Hi,

If I got it correctly patch is just a combination of updateIn, setIn, deleteIn?

**Comment by tgriesser** [comment]
Not sure the question, but patch is defined here https://tools.ietf.org/html/rfc6902 and is required to be a string, which doesn't work without some extra parsing if some of the keys in your immutable maps are numbers.

**Comment by azproduction** [comment]
@tgriesser thanks!
